# -*- coding: utf-8 -*-
"""Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import random

# =========================================================
# CONFIGURASAUN PÁJINA
# =========================================================

st.set_page_config(
    page_title="Math Challenge - Klase 5 & 6",
    page_icon="🧮",
    layout="centered"
)

# =========================================================
# CSS - INTERFACE ATRATIVU
# =========================================================

st.markdown("""
<style>

.main {
    background-color: #f5f7fb;
}

.title {
    text-align: center;
    font-size: 42px;
    font-weight: bold;
    margin-bottom: 5px;
}

.subtitle {
    text-align: center;
    font-size: 20px;
    margin-bottom: 25px;
}

.question-box {
    padding: 25px;
    border-radius: 20px;
    background-color: #ffffff;
    text-align: center;
    box-shadow: 0px 4px 12px rgba(0,0,0,0.10);
    margin: 20px 0px;
}

.question {
    font-size: 38px;
    font-weight: bold;
}

.score-box {
    padding: 15px;
    border-radius: 15px;
    background-color: #ffffff;
    text-align: center;
    font-size: 22px;
    font-weight: bold;
    margin-bottom: 15px;
}

.result-box {
    padding: 25px;
    border-radius: 20px;
    background-color: #ffffff;
    text-align: center;
    box-shadow: 0px 4px 12px rgba(0,0,0,0.12);
}

</style>
""", unsafe_allow_html=True)

# =========================================================
# FUNSAUN KREA PERGUNTA
# =========================================================

def create_question(grade):

    # -------------------------
    # KLASSE 5
    # -------------------------
    if grade == "Klase 5":

        operation = random.choice(["+", "-", "×", "÷"])

        if operation == "+":
            a = random.randint(100, 999)
            b = random.randint(100, 999)
            answer = a + b

        elif operation == "-":
            a = random.randint(200, 999)
            b = random.randint(100, a)
            answer = a - b

        elif operation == "×":
            a = random.randint(2, 20)
            b = random.randint(2, 12)
            answer = a * b

        else:
            b = random.randint(2, 12)
            answer = random.randint(2, 20)
            a = b * answer

        question = f"{a} {operation} {b} = ?"

    # -------------------------
    # KLASSE 6
    # -------------------------
    else:

        operation = random.choice(["+", "-", "×", "÷"])

        if operation == "+":
            a = random.randint(500, 4999)
            b = random.randint(500, 4999)
            answer = a + b

        elif operation == "-":
            a = random.randint(1000, 9999)
            b = random.randint(100, a)
            answer = a - b

        elif operation == "×":
            a = random.randint(10, 99)
            b = random.randint(2, 20)
            answer = a * b

        else:
            b = random.randint(2, 20)
            answer = random.randint(5, 100)
            a = b * answer

        question = f"{a} {operation} {b} = ?"

    return question, answer


# =========================================================
# INICIALIZA SESSION STATE
# =========================================================

if "started" not in st.session_state:
    st.session_state.started = False

if "finished" not in st.session_state:
    st.session_state.finished = False

if "question_number" not in st.session_state:
    st.session_state.question_number = 1

if "score" not in st.session_state:
    st.session_state.score = 0

if "correct" not in st.session_state:
    st.session_state.correct = 0

if "questions" not in st.session_state:
    st.session_state.questions = []

if "answers" not in st.session_state:
    st.session_state.answers = []

# =========================================================
# TITULU
# =========================================================

st.markdown(
    '<div class="title">🧮 Math Challenge</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🎯 Aprende Matemática ho Jogu!</div>',
    unsafe_allow_html=True
)

# =========================================================
# MENU INICIAL
# =========================================================

if not st.session_state.started:

    st.info(
        "🎮 Jogu ida ne'e iha perguntas 10 deit. "
        "Tenta responde hotu no hetan skor aas liu!"
    )

    grade = st.selectbox(
        "📚 Hili ita-nia klase:",
        ["Klase 5", "Klase 6"]
    )

    st.markdown("### 🎲 Operasaun Disponível")

    col1, col2 = st.columns(4)

    with col1:
        st.write("➕")
        st.caption("Adisaun")

    with col2:
        st.write("➖")
        st.caption("Subtrasaun")

    with col3:
        st.write("✖️")
        st.caption("Multiplikasaun")

    with col4:
        st.write("➗")
        st.caption("Divisaun")

    if st.button("🚀 Hahu Jogu", use_container_width=True):

        st.session_state.grade = grade
        st.session_state.started = True
        st.session_state.finished = False
        st.session_state.question_number = 1
        st.session_state.score = 0
        st.session_state.correct = 0
        st.session_state.questions = []
        st.session_state.answers = []

        # Krea perguntas 10 deit
        for _ in range(10):
            q, ans = create_question(grade)
            st.session_state.questions.append((q, ans))

        st.rerun()


# =========================================================
# JOGU
# =========================================================

elif st.session_state.started and not st.session_state.finished:

    q_number = st.session_state.question_number

    # -----------------------------------------
    # PROGRESSO
    # -----------------------------------------

    st.progress(q_number / 10)

    col1, col2 = st.columns(2)

    with col1:
        st.write(f"📌 Pergunta **{q_number} / 10**")

    with col2:
        st.write(f"🏆 Skor: **{st.session_state.score}**")

    # -----------------------------------------
    # PERGUNTA
    # -----------------------------------------

    question, correct_answer = st.session_state.questions[q_number - 1]

    st.markdown(
        f"""
        <div class="question-box">
            <div class="question">{question}</div>
        </div>
        """,
        unsafe_allow_html=True
    )

    # -----------------------------------------
    # RESPOSTA
    # -----------------------------------------

    answer = st.number_input(
        "✏️ Hakerek resposta:",
        step=1,
        key=f"answer_{q_number}"
    )

    # -----------------------------------------
    # BOTÃO RESPONDE
    # -----------------------------------------

    if st.button(
        "✅ Responde",
        use_container_width=True,
        key=f"submit_{q_number}"
    ):

        # Prevén klik repetidu
        if f"answered_{q_number}" not in st.session_state:

            st.session_state[f"answered_{q_number}"] = True

            if answer == correct_answer:

                st.session_state.score += 1
                st.session_state.correct += 1

                st.success(
                    f"🎉 Loos! {question.replace('?', str(correct_answer))}"
                )

            else:

                st.error(
                    f"❌ Sala. Resposta loos mak **{correct_answer}**."
                )

            # Guarda resposta
            st.session_state.answers.append(
                {
                    "question": question,
                    "student_answer": answer,
                    "correct_answer": correct_answer
                }
            )

            # -----------------------------------------
            # VERIFIKA SE PERGUNTA 10 REMATA
            # -----------------------------------------

            if q_number == 10:

                st.session_state.finished = True

            else:

                st.session_state.question_number += 1

            st.rerun()


# =========================================================
# RESULTADU FINAL
# =========================================================

elif st.session_state.finished:

    st.balloons()

    score = st.session_state.score
    correct = st.session_state.correct

    st.markdown(
        """
        <div class="result-box">
            <h1>🏆 Jogu Remata!</h1>
            <h2>🎯 Ita responde perguntas 10 hotu.</h2>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    # -----------------------------------------
    # RESULTADU
    # -----------------------------------------

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "🏆 Skor",
            f"{score}/10"
        )

    with col2:
        st.metric(
            "✅ Los",
            correct
        )

    with col3:
        st.metric(
            "❌ Sala",
            10 - correct
        )

    # -----------------------------------------
    # MENSAGEM
    # -----------------------------------------

    if score == 10:
        st.success(
            "🌟 Excelente! Ita domina operasaun bazika matemática!"
        )

    elif score >= 8:
        st.success(
            "👏 Muito diak! Ita iha abilidade matemática ne'ebé forte!"
        )

    elif score >= 6:
        st.info(
            "👍 Diak! Kontinua pratika atu aumenta ita-nia skor!"
        )

    elif score >= 4:
        st.warning(
            "💪 Kontinua aprende! Pratika adisaun, subtrasaun, "
            "multiplikasaun no divisaun tan."
        )

    else:
        st.error(
            "📚 Presiza pratika tan. La bele desiste!"
        )

    # -----------------------------------------
    # RESULTADU DETALHADU
    # -----------------------------------------

    st.subheader("📋 Rezultadu Pergunta")

    for i, item in enumerate(st.session_state.answers, start=1):

        question = item["question"]
        student_answer = item["student_answer"]
        correct_answer = item["correct_answer"]

        if student_answer == correct_answer:

            st.write(
                f"**{i}.** {question} "
                f"➡️ ✅ {student_answer}"
            )

        else:

            st.write(
                f"**{i}.** {question} "
                f"➡️ ❌ Ita hatán: {student_answer} | "
                f"Loos: {correct_answer}"
            )

    st.write("")

    # -----------------------------------------
    # BOTÃO JOGA FALI
    # -----------------------------------------

    if st.button(
        "🔄 Joga Fali",
        use_container_width=True
    ):

        # Reset
        for key in list(st.session_state.keys()):
            del st.session_state[key]

        st.rerun()

    st.info(
        "ℹ️ Jogu ida ne'e remata depois de perguntas 10. "
        "Klik 'Joga Fali' se ita hakarak halo tentativa foun."
    )